# The QSim Library:

QSim is a library that attempts to allow one to perform a few basic quantum circuit simulation related operations. Find the code on QSim.py

In [1]:
from QSim import *

## Quantum Gates

QSim has many gates and functions predefined into it. The following are a few examples:

In [2]:
print("Hadamard:\n "+ str(H)+ '\n')
print("NOT:\n " + str(X)+ '\n')
print("CNOT:\n " + str(CNOT)+ '\n')
print("Identity:\n" + str(I)+ '\n')
print("|0>:\n" + str(zero)+ '\n')
print("|1>:\n" + str(one)+ '\n')
print("Bell of 11:\n" + str(B11)+ '\n')
print("Rx of pi:\n" + str(Rx(np.pi))+ '\n')

Hadamard:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

NOT:
 [[0 1]
 [1 0]]

CNOT:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]

Identity:
[[1. 0.]
 [0. 1.]]

|0>:
[[1]
 [0]]

|1>:
[[0]
 [1]]

Bell of 11:
[[ 0.        ]
 [-0.70710678]
 [ 0.70710678]
 [ 0.        ]]

Rx of pi:
[[6.123234e-17+0.j 0.000000e+00-1.j]
 [0.000000e+00-1.j 6.123234e-17+0.j]]



## Get the Ground State Statevector

QSim has a function which gets the ground state statevector of an n-qubit circuit. It goes as follows:

In [3]:
initial = get_ground_state(3)
print(initial)
initial.shape

[1 0 0 0 0 0 0 0]


(8,)

## Get operator

Function that returns the matrix operator of a gate being acted on a target qubit in an n-qubit circuit. The number of dimensions are $2^n \times 2^n$.

This function is friendly to all 1 qubit gates and CNOT gates

The following is an example of applying a Hadamard to the 0th qubit in a 2 qubit circuit:

In [4]:
get_operator(2, H, 0)

array([[ 0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.70710678],
       [ 0.70710678,  0.        , -0.70710678, -0.        ],
       [ 0.        ,  0.70710678, -0.        , -0.70710678]])

## View operator
 
Returns the same as get_operator() but with clearer syntax

In [5]:
def view_operator(a,b,c):
    mat = get_operator(a,b,c)
    return display(Matrix(mat))

view_operator(2, H, 0)

Matrix([
[0.707106781186547,               0.0,  0.707106781186547,                0.0],
[              0.0, 0.707106781186547,                0.0,  0.707106781186547],
[0.707106781186547,               0.0, -0.707106781186547,                0.0],
[              0.0, 0.707106781186547,                0.0, -0.707106781186547]])

## Run circuit

This is the function that actually runs the circuit and transforms an inital statevector to a final one. 

The syntax is run_program(initial, circuit)

where initial is a list of lenth $2^n$

and circ is a list of dictionaries with syntax [{ "gate": gate_unitary, "target": target_qubit }, { "gate": gate_unitary, "target": target_qubit },...]

The following is a hadamard being applied to the 0th qubit in a 1 qubit circuit:

In [6]:
run_program([1,0], [{ "gate": H, "target": 0 }])

array([0.70710678, 0.70710678])

## Measure State

This returns the probability of each possible state given a statevector. The following is an application of the circuit ran above:

In [7]:
measure([0.70710678, 0.70710678, 0, 0])

0: 0.5
1: 0.5
10: 0
11: 0


## Get Counts

Uses weight random measurement to "collapse the wavefunction" n amount of times and gives the found probabilities in a list. The syntax is get_counts(state_vector, n_counts)
The following is an example of the result of the same state_vector given in "Measure state" with 50 counts:


In [8]:
get_counts([0.70710678, 0.70710678, 0, 0],50)

[0.52, 0.48, 0.0, 0.0]

## Example: Demonstrating Quantum Enganglement with QSim

The following is a program which utilizes QSim to simulate the $| \phi^+ \rangle$ Bell State. This is a 2-qubit circuit with a Hadamard on q0 and a CNOT on q0,q1. The output should suggest entanglement

In [9]:
n_qubits = 2

ground_state = get_ground_state(n_qubits)

circ = [{ "gate": H, "target": 0 },{ "gate": CNOT, "target": [0,1]}]

statevector = run_program(ground_state, circ)

print(' Phi+ Statevector: ')
view(statevector)
print('\n')
print('Probabilities: ')
measure(statevector)
print('\n')
print('Results over 1024 count iterations: ')

get_counts(statevector, 1024)

 Phi+ Statevector: 


Matrix([
[0.707106781186547],
[              0.0],
[              0.0],
[0.707106781186547]])



Probabilities: 
0: 0.5
1: 0.0
10: 0.0
11: 0.5


Results over 1024 count iterations: 


[0.5263671875, 0.0, 0.0, 0.4736328125]